# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Uconnection_Homework' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'Moya'
pod 'Kingfisher'
pod 'Moya/RxSwift'
pod 'RxCocoa'

  # Pods for Uconnection_Homework

end
